# Generated by Django 5.0.2 on 2024-02-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_category_article_main_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
