# Generated by Django 5.0.2 on 2024-02-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_image_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_2',
        ),
    ]
